### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kevlened** [moifort/liquidfire#1]
Hi Thibaut

I'm glad you like the [fireway](https://github.com/kevlened/fireway) library. You liked it enough to create modifications and publish them (that's great!). The only caveat is the way you did it violates [the MIT license here](https://github.com/kevlened/fireway/blob/master/LICENSE):

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

To fix the issue, just copy my LICENSE file into this repo. Feel free to append your own license for the modifications.

Cheers

**Comment by moifort** [comment]
Hey @kevlened,

My bad, thanks for your lib! 

I will make the fix!

**Comment by kevlened** [comment]
As an example, here's a lib with two MIT licenses:
https://github.com/shopspring/decimal/blob/master/LICENSE

**Comment by moifort** [comment]
Link #2
